import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { NextResponse } from "next/server"

export async function POST(req: Request) {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) return new NextResponse("Unauthorized", { status: 401 })

    try {
        const { content } = await req.json()

        if (!content) return new NextResponse("Content is required", { status: 400 })

        // Mock AI Summarization
        // In a real app, call OpenAI/Anthropic/Gemini API here
        const summary = `**AI Summary:**\n\nThis note discusses key points regarding the project. It highlights important tasks, decisions made, and next steps. (This is a mock summary generated by the system).`

        // Simulate network delay
        await new Promise(resolve => setTimeout(resolve, 1500))

        return NextResponse.json({ summary })
    } catch (error) {
        console.error("Failed to summarize:", error)
        return new NextResponse("Internal Server Error", { status: 500 })
    }
}
